apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: medcare-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: medcare-webapi-config
    literals:
      - database=medcare-db
      - collection=allergy_records:allergy_records,lab_results:lab_results,medical_records:medical_records,vaccination_records:vaccination_records

patches:
  - path: patches/webapi.deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: medcare-webapi
