/*
 * MedCare API
 *
 * MedCare system API
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package medcare_api

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type VaccinationRecordsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateVaccinationRecord - Create a new vaccination record
   CreateVaccinationRecord(ctx *gin.Context)

    // GetAllVaccinationRecords - Get all vaccination records
   GetAllVaccinationRecords(ctx *gin.Context)

 }

 // partial implementation of VaccinationRecordsAPI - all functions must be implemented in add on files
type implVaccinationRecordsAPI struct {

}

func newVaccinationRecordsAPI() VaccinationRecordsAPI {
  return &implVaccinationRecordsAPI{}
}

func (this *implVaccinationRecordsAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/vaccination-records", this.CreateVaccinationRecord)
  routerGroup.Handle( http.MethodGet, "/vaccination-records", this.GetAllVaccinationRecords)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateVaccinationRecord - Create a new vaccination record
// func (this *implVaccinationRecordsAPI) CreateVaccinationRecord(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAllVaccinationRecords - Get all vaccination records
// func (this *implVaccinationRecordsAPI) GetAllVaccinationRecords(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

