/*
 * MedCare API
 *
 * MedCare system API
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medcare_api

type MedicalRecord struct {

	// Unique id of the medical record
	Id string `json:"id"`

	// Unique identifier of the patient
	PatientId string `json:"patientId"`

	Condition string `json:"condition"`

	Treatment string `json:"treatment"`

	History string `json:"history,omitempty"`
}
