// /*
//  * MedCare API
//  *
//  * MedCare system API
//  *
//  * API version: 1.0.0
//  * Contact: <your_email>
//  * Generated by: OpenAPI Generator (https://openapi-generator.tech)
//  */

// package medcare

// import (
// 	"net/http"

// 	"github.com/gin-gonic/gin"
// )

// type MedicalRecordsAPI interface {
// 	// internal registration of api routes
// 	addRoutes(routerGroup *gin.RouterGroup)

// 	// GetAllMedicalRecords - Get all medical records
// 	GetAllMedicalRecords(ctx *gin.Context)
// }

// // partial implementation of MedicalRecordsAPI - all functions must be implemented in add on files
// type implMedicalRecordsAPI struct {
// }

// func newMedicalRecordsAPI() MedicalRecordsAPI {
// 	return &implMedicalRecordsAPI{}
// }

// func (this *implMedicalRecordsAPI) addRoutes(routerGroup *gin.RouterGroup) {
// 	routerGroup.Handle(http.MethodGet, "/medical-records", this.GetAllMedicalRecords)
// }

// // GetAllMedicalRecords - Get all medical records
// func (this *implMedicalRecordsAPI) GetAllMedicalRecords(ctx *gin.Context) {
// 	ctx.AbortWithStatus(http.StatusNotImplemented)
// }

package medcare

import (
	"net/http"

	"github.com/DanielCok17/medcare-webapi/internal/db_service"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

type implMedicalRecordsAPI struct{}

// CreateMedicalRecord - Saves new medical record
func (this *implMedicalRecordsAPI) CreateMedicalRecord(ctx *gin.Context) {
	value, exists := ctx.Get("medical_record_db_service")
	if !exists {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db not found",
			"error":   "db not found",
		})
		return
	}

	db, ok := value.(db_service.DbService[MedicalRecord])
	if !ok {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db context is not of required type",
			"error":   "cannot cast db context to db_service.DbService",
		})
		return
	}

	medicalRecord := MedicalRecord{}
	err := ctx.BindJSON(&medicalRecord)
	if err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{
			"status":  "Bad Request",
			"message": "Invalid request body",
			"error":   err.Error(),
		})
		return
	}

	if medicalRecord.Id == "" {
		medicalRecord.Id = uuid.New().String()
	}

	err = db.CreateDocument(ctx, medicalRecord.Id, &medicalRecord)
	if err != nil {
		switch err {
		case db_service.ErrConflict:
			ctx.JSON(http.StatusConflict, gin.H{
				"status":  "Conflict",
				"message": "Medical record already exists",
				"error":   err.Error(),
			})
		default:
			ctx.JSON(http.StatusBadGateway, gin.H{
				"status":  "Bad Gateway",
				"message": "Failed to create medical record in database",
				"error":   err.Error(),
			})
		}
		return
	}

	ctx.JSON(http.StatusCreated, medicalRecord)
}

// GetAllMedicalRecords - Get all medical records
func (this *implMedicalRecordsAPI) GetAllMedicalRecords(ctx *gin.Context) {
	value, exists := ctx.Get("medical_record_db_service")
	if !exists {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db not found",
			"error":   "db not found",
		})
		return
	}

	db, ok := value.(db_service.DbService[MedicalRecord])
	if !ok {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db context is not of required type",
			"error":   "cannot cast db context to db_service.DbService",
		})
		return
	}

	records, err := db.FindAllDocuments(ctx)
	if err != nil {
		ctx.JSON(http.StatusBadGateway, gin.H{
			"status":  "Bad Gateway",
			"message": "Failed to fetch medical records from database",
			"error":   err.Error(),
		})
		return
	}

	ctx.JSON(http.StatusOK, records)
}

// GetMedicalRecordById - Get medical record by ID
func (this *implMedicalRecordsAPI) GetMedicalRecordById(ctx *gin.Context) {
	value, exists := ctx.Get("medical_record_db_service")
	if !exists {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db not found",
			"error":   "db not found",
		})
		return
	}

	db, ok := value.(db_service.DbService[MedicalRecord])
	if !ok {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db context is not of required type",
			"error":   "cannot cast db context to db_service.DbService",
		})
		return
	}

	recordId := ctx.Param("recordId")
	record, err := db.FindDocument(ctx, recordId)
	if err != nil {
		ctx.JSON(http.StatusNotFound, gin.H{
			"status":  "Not Found",
			"message": "Medical record not found",
			"error":   err.Error(),
		})
		return
	}

	ctx.JSON(http.StatusOK, record)
}

// DeleteMedicalRecord - Delete a medical record
func (this *implMedicalRecordsAPI) DeleteMedicalRecord(ctx *gin.Context) {
	value, exists := ctx.Get("medical_record_db_service")
	if !exists {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db not found",
			"error":   "db not found",
		})
		return
	}

	db, ok := value.(db_service.DbService[MedicalRecord])
	if !ok {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"status":  "Internal Server Error",
			"message": "db context is not of required type",
			"error":   "cannot cast db context to db_service.DbService",
		})
		return
	}

	recordId := ctx.Param("recordId")
	err := db.DeleteDocument(ctx, recordId)
	if err != nil {
		ctx.JSON(http.StatusNotFound, gin.H{
			"status":  "Not Found",
			"message": "Medical record not found",
			"error":   err.Error(),
		})
		return
	}

	ctx.Status(http.StatusNoContent)
}

// addRoutes - Adds routes for medical records API
func (api *implMedicalRecordsAPI) addRoutes(group *gin.RouterGroup) {
	group.POST("/medical_records", api.CreateMedicalRecord)
	group.GET("/medical_records", api.GetAllMedicalRecords)
	group.GET("/medical_records/:recordId", api.GetMedicalRecordById)
	group.DELETE("/medical_records/:recordId", api.DeleteMedicalRecord)
}
