/*
 * MedCare API
 *
 * MedCare system API
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medcare

type AllergyRecord struct {

	// Unique id of the allergy record
	Id string `json:"id"`

	// Unique identifier of the patient
	PatientId string `json:"patientId"`

	Allergen string `json:"allergen"`
}
