// /*
//  * MedCare API
//  *
//  * MedCare system API
//  *
//  * API version: 1.0.0
//  * Contact: <your_email>
//  * Generated by: OpenAPI Generator (https://openapi-generator.tech)
//  */

// package medcare

// import (
//     "github.com/gin-gonic/gin"
// )

// func AddRoutes(engine *gin.Engine) {
//   group := engine.Group("/api")

//   {
//     api := newAllergyRecordsAPI()
//     api.addRoutes(group)
//   }

//   {
//     api := newLabResultsAPI()
//     api.addRoutes(group)
//   }

//   {
//     api := newMedicalRecordsAPI()
//     api.addRoutes(group)
//   }

//   {
//     api := newVaccinationRecordsAPI()
//     api.addRoutes(group)
//   }

// }

package medcare

import (
	"github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
	group := engine.Group("/api")

	allergyRecordsAPI := newAllergyRecordsAPI()
	allergyRecordsAPI.addRoutes(group)

	labResultsAPI := newLabResultsAPI()
	labResultsAPI.addRoutes(group)

	medicalRecordsAPI := newMedicalRecordsAPI()
	medicalRecordsAPI.addRoutes(group)

	vaccinationRecordsAPI := newVaccinationRecordsAPI()
	vaccinationRecordsAPI.addRoutes(group)
}

func newAllergyRecordsAPI() *implAllergyRecordsAPI {
	return &implAllergyRecordsAPI{}
}

func newLabResultsAPI() *implLabResultsAPI {
	return &implLabResultsAPI{}
}

func newMedicalRecordsAPI() *implMedicalRecordsAPI {
	return &implMedicalRecordsAPI{}
}

func newVaccinationRecordsAPI() *implVaccinationRecordsAPI {
	return &implVaccinationRecordsAPI{}
}
