/*
 * MedCare API
 *
 * MedCare system API
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medcare

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newAllergyRecordsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newLabResultsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newMedicalRecordsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newVaccinationRecordsAPI()
    api.addRoutes(group)
  }
  
}